Repository linux-nvme/nvme-cli, pull requests merged in 2022-01, with the labels that each got.

#1304 [nvme-cli] Fix vs-smart-add-log bug to retrieve customer id
  plugins/wdc/wdc-nvme.c
Labels: bug

#1302 Fix help message fid support effects log
  nvme-builtin.h
Labels: bug

#1290 nvme: support ns generic device to submit_io
  nvme-private.h
  nvme.c
  nvme.h
Labels: enhancement

#1297 Add OpenSSL 3 support for dhchap-key generation
  meson.build
  meson_options.txt
  nvme.c
  subprojects/openssl.wrap
Labels: bug, enhancement
